services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: "laravel"
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "nginx"
    # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
    ports:
      - 80:80
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www
    # サービスの依存関係を指定（nginxをphpに依存させる）
    depends_on:
      - laravel
