services:
  laravel:
    image: laravel:latest
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
    ports:
      - 80:80
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www
    # サービスの依存関係を指定（nginxをphpに依存させる）
    depends_on:
      - laravel

  node:
    image: node:latest
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    # viteのデフォルトポートを解放
    ports:
      - 5173:5173
    # コンテナ内の標準出力とホストの出力を設定：trueを指定
    tty: true
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www
    # コンテナ起動後のカレントディレクトリを設定
    working_dir: /var/www
