name: CI flow

on: [push, workflow_dispatch]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: docker up
        run: docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d

      - name: Get Composer Cache Directory
        id: composer-cache
        run: docker compose exec laravel echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker compose exec laravel composer install -n --prefer-dist

      - name: copy .env
        run: docker compose exec laravel cp .env.example .env

      - name: generate key
        run: docker compose exec laravel php artisan key:generate

      - name: Create Database
        run: |
          docker compose exec laravel mkdir -p database
          docker compose exec laravel touch database/database.sqlite

      - name: migrate
        run: docker compose exec -e DB_CONNECTION=sqlite -e DB_DATABASE=database/database.sqlite laravel php artisan migrate:refresh --seed

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"

      - name: unit test
        run: docker compose exec -e DB_CONNECTION=sqlite -e DB_DATABASE=database/database.sqlite laravel php artisan test --filter http
